### ISSUE TITLE
It requires 'res_LSTM' folder in 'codes' folder

### ISSUE THREAD

**Issue by yyc9268** [kezhang-cs/Video-Summarization-with-LSTM#1]
When I tried to run the code, it returned error that it is unable to create file like below.

IOError: Unable to create file (unable to open file: name = './res_LSTM//dppLSTM_SumMe_2_inference.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)

This is a simple error, but it could make confusion.
I solved this by manually creating folder the 'res_LSTM' folder.
Please check this.

Thank you.

**Comment by ra1995** [comment]
@yyc9268 I managed to run the code, but can you help me in how to interpret the resulting H5 files for both dpp_lstm and vs_lstm.

I see there are 4 fields in dpp_lstm inference file namely
cfrm, idx, pred and predk
what do they stand for.

Please help me out.
Thanks.

**Comment by kezhang-cs** [comment]
@yyc9268 Yes, you need to create a folder called 'res_LSTM'

**Comment by kezhang-cs** [comment]
@ra1995 Hi,

pred and predk are the corresponding prediction of y_i for each frame and \phi_i for DPP. 

cfrm and idx are to specify each video, look them up in the eval.m.

Thanks.
