### ISSUE TITLE
Interpreting the dataset

### ISSUE THREAD

**Issue by ayushkothari27** [kezhang-cs/Video-Summarization-with-LSTM#17]
@kezhang-cs Hello,
I see there are two fields in the dataset - `gt_1_i` and `gt_2_i`. Can you explain the difference and significance of these? I see that you have used `gt_1_i` in your code while calculating losses. In the readme file, you have written `gt_1_i` is the frame-level importance scores while `gt_2_i` is the binary value transferred from the original dataset. I couldn't understand this part.
Thank you.

**Comment by ritvik2708** [comment]
Hey @aayushkothari11 I think gt_1_i is groundTruth_1 for ith sample and similarly for gt_2_i. gt_1 gives the outputs for the summary in soft values i.e. grey values b/w 0 and 1 while gt_2 provides a binary values which indicates either the frame is part of gt else it is not.

**Comment by Chen414** [comment]
Hello, l also need the datasets, but the link is not available, can you send the datasets to my emails 644109863@qq.com?
I'll be very grateful to you~Thank~

**Comment by Chen414** [comment]
Hello@ritvik2708, l also need the datasets, but the link is not available, can you send the datasets to my emails 644109863@qq.com?
I'll be very grateful to youThank
