### ISSUE TITLE
Video preprocessing code

### ISSUE THREAD

**Issue by SteveTrabajoJr** [kezhang-cs/Video-Summarization-with-LSTM#2]
Can u pls provide code you used for preprocessing of videos?

Thank you

**Comment by kezhang-cs** [comment]
We used caffe to extract feature for each frame, the code is available from here:
https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet

**Comment by TriLoo** [comment]
I wonder if there is other post-processes to the extracted features ? Because the extracted features by the given caffe model cannot match the features from `.h5` file, actually, there is a big difference between the two array ...

any advices ? thanks
